### PR TITLE
Removed old code ignoring bucket amounts above 1 Fixes #2171"

### LINKED ISSUE #2171: Recipes with more than one Bucket of fluid do not get transferred from JEI
#### Issue description:
When making Patterns via JEI, recipes that have more than 1 Bucket of fluid do not get inserted into the recipe.
#### What happens:
Fluid is just missing from the recipe

#### What you expected to happen:
Fluid is added like normal

#### Steps to reproduce:
1. Set up pattern grid in processing mode
2. Find a recipe with more than 1 Bucket of fluid (Phytogenic Insolator has some)
3. Notice missing fluid
...
####Additional info
Probably related to #1953

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12
- Forge:2795
- Refined Storage:1.6.12
Does this issue occur on a server? [yes/no]
yes

### PR DESCRIPTION
**Pull request by Darkere**
Fixes #2171

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Thx, will merge this later.

**Comment by raoulvdberge** [comment]
@Darkere: Please revert your last commit. I was not intending in adding / merging such a feature;

**Comment by Darkere** [comment]
Oh, I did not even realize that got included. I mostly wanted that one for myself. 
Although I would love to see the feature, I think implementing it properly would break the API and that's probably not worth doing for just that.

**Comment by raoulvdberge** [comment]
Thaanks!

**Pull request merged**
