### PR TITLE
Store Energy in item when ccontrolelr is broken

### PR DESCRIPTION
**Pull request by tomevoll**
```
modified:   src/main/java/refinedstorage/block/BlockController.java
modified:   src/main/java/refinedstorage/tile/TileController.java
```

### CODE REVIEW

**Comment by tomevoll** [comment]
this also store any redstone mode set on the controller

**Comment by tomevoll** [comment]
im not sure if this work with silk harvest, might wanna try that and add the item generation there to, i can look at that a litle later, gotta take a break atm

**Comment by tomevoll** [comment]
setEnergyStored can be removed from the tile again, since i switched to using NBT directly instead, found that to be beter since any values you write to nbt will be restored then, just make sure to not use super.writetonbt or read in there, as that will throw an error since the tileentity position is written then.

**Comment by tomevoll** [comment]
lol hopefully the code works better then the title, not sure what world i was in when i typed that :P

**Comment by raoulvdberge** [comment]
I think it is a better idea to just make an ItemBlock, it would be much cleaner.

See https://github.com/raoulvdberge/refinedstorage/blob/mc1.9/src/main/java/refinedstorage/block/BlockStorage.java

**Comment by tomevoll** [comment]
hmm, getDroppedItems, are you sure that works? i tried that on controller and getting the tile there its always null, its already invalid at harvestBlock

**Comment by raoulvdberge** [comment]
Yeah, that code works. You *need* the `removedByPlayer` and `harvestBlock` stuff too.

**Comment by tomevoll** [comment]
harvest block i did, but i tried getDrops and i was unable to get the tile there witch is why i added a modified harvestBlock function, i will look at it again, world.getTile...  always gave me null back

**Comment by raoulvdberge** [comment]
Did you add these 2 functions?
```java
    @Override
    public boolean removedByPlayer(IBlockState state, World world, BlockPos pos, EntityPlayer player, boolean willHarvest) {
        if (willHarvest) {
            return true;
        }

        return super.removedByPlayer(state, world, pos, player, willHarvest);
    }

    @Override
    public void harvestBlock(World world, EntityPlayer player, BlockPos pos, IBlockState state, TileEntity tile, ItemStack stack) {
        super.harvestBlock(world, player, pos, state, tile, stack);

        world.setBlockToAir(pos);
    }
```

**Comment by tomevoll** [comment]
not removedByPlayer, im redoing it now with itemblock

**Comment by tomevoll** [comment]
you are right that did work :)

**Comment by tomevoll** [comment]
hmm, seems im missing the correct state as its not rendering the power level on the item

**Comment by raoulvdberge** [comment]
I can do the item rendering stuff...

**Comment by raoulvdberge** [comment]
Why are you checking if energyStored > 0?

`if (energyStored > 0) this.energy.setEnergyStored(energyStored);`

**Comment by raoulvdberge** [comment]
In the `initNBT` method you forgot to set the itemstack's energy to 0...

**Comment by tomevoll** [comment]
> 

Why are you checking if energyStored > 0?

if (energyStored > 0) this.energy.setEnergyStored(energyStored);


in case a negative value is read from NBT fro some unknown reason, but that function can be removed, i just forgott to remove it.

**Comment by tomevoll** [comment]
dont need to set it to 0 in init unless you want it to show 0/....  when no energy is stored in it.

**Comment by tomevoll** [comment]
should be better no need to do the same code 2 times

**Comment by raoulvdberge** [comment]
I'll merge this if you change following things:
- Remove writeItemToNBT and readItemFromNBT, you can just call readNBT and writeNBT directly
- The energy should show up by default in the tooltip, even if it's not placed yet, so make initNBT default to 0, or, if it's a creative controller to ENERGY_CAPACITY

**Comment by tomevoll** [comment]
ok

**Comment by raoulvdberge** [comment]
Thanks!

**Comment by tomevoll** [comment]
change: 
EnumControllerType type = EnumControllerType.values()[stack.getMetadata()];

TO:

EnumControllerType type = stack.getMetadata() == 1 ? EnumControllerType.CREATIVE : EnumControllerType.NORMAL;

in init and addinfo, some reason it crashes on values()

**Pull request merged**
