### PR TITLE
Fix incorrect autocraft prompt on macOS

### PR DESCRIPTION
**Pull request by alyxandraio**
On macOS, JEI's autofill/autocraft button prompts the user for `Ctrl + Click`, but the actual keybind is `Cmd + Click`. This branch fixes this and adds Japanese translations for a couple autocrafting keys.

### CODE REVIEW

**Comment by alyxandraio** [comment]
Also, I've verified that the `os.name` property still returns `Mac OS X` on the latest version, despite the name change to macOS.

**Review by raoulvdberge — CHANGES_REQUESTED** [review]
Thanks, can you add a changelog entry?

**Comment by alyxandraio** [comment]
Should be good now, sorry that took me so long. @raoulvdberge

**Comment by raoulvdberge** [comment]
Hi @alyxferrari ! Sorry, still didn't get around to merging this. There is a merge conflict on `CHANGELOG.md`, could you fix that? Then I can merge. Thanks!

**Comment by alyxandraio** [comment]
@raoulvdberge Was away from my computer for a bit. Should be good to go! 😁

**Review by raoulvdberge — APPROVED** [review]

**Pull request merged**
