### PR TITLE
fix blockupdates always invalidating storage fixes #2568 #2631

### LINKED ISSUE #2568: [1.15.2] Can't remove items from RS grid when connected to DimStorage chest
#### Issue description:
When I connect a dimstorage chest to my RS system using the external storage I can't take any items from my RS grid. Not just the items from the dimstorage chest. I already reported it on the dimstorage github but they told me I should contact you: https://github.com/Edivad99/DimStorage/issues/27

#### Steps to reproduce:
1. Connect a dimstorage chest to an RS system using external storage. 
2. Try to remove items from the RS system (not only the items from the chest but also from drives). If you're fast enough you might be able to take something once but not after that.

#### Versions:

- Minecraft: 1.15.2
- Forge: 31.2.9
- Refined Storage: 1.8.4
- DimStorage: 3.1.5

Does this issue occur on a server? [yes/no]
Yes

### PR DESCRIPTION
**Pull request by Darkere**
This should fix issues with being unable to extract items from the grid. 
Hopeful this doesn't have any side effects but not can't really guarantee that. 

Can't really think of a case where this fails though.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
What if you just open a world with the external storage and connected block present? Then no block update is fired, which means it would still break on the first update.

**Comment by raoulvdberge** [comment]
What I mean is that `connectedBlockState ` is only setup right after the update request. But it isn't set when the world loads, causing a invalidation anyway for the first time.

**Comment by Darkere** [comment]
Now I understood :)

**Comment by raoulvdberge** [comment]
I discussed with Darkere. We will not be merging this for RS 1 because RS 2 is in active development and we don't want to risk breakage of any sort on RS 1 at this point.

**Pull request closed without merging**
