### PR TITLE
Allow simple math input in AmountSpecifyingScreen

### LINKED ISSUE #2728: [feature request] allow basic Math in crafting requests
Feature Request to allow basic math when autocrafting items. Helpfull for bigger projects, i.e. you need 8 upgrades each for 26 pumps.

YPuVXCO

### PR DESCRIPTION
**Pull request by yihualou**
Fixes https://github.com/refinedmods/refinedstorage/issues/2728.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Thanks! Could you add a changelog entry?

**Comment by yihualou** [comment]
Done.

**Review by raoulvdberge — APPROVED** [review]

**Comment by raoulvdberge** [comment]
Thank you!

**Comment by raoulvdberge** [comment]
This PR is not very well tested, I found a lot of last minute bugs like the +1 button no longer working, the evaluator just crashing on empty text fields. There are probably some more bugs I didn't find. Therefore I'm reverting this PR, as 1.18 will most likely not get any more updates and we need a stable version.

**Pull request merged**
