### PR TITLE
Fixes RF draw incorrect

### PR DESCRIPTION
**Pull request by tomevoll**
sorry for the clean commits in it lol, tried to match the spaces to minimize changes, for some reason it refuses to pull into that fork, even though it says it did it lol

### CODE REVIEW

**Comment by tomevoll** [comment]
about the bug i mentioned with redstone, that is if redstone is set to ignore. not sure if maybe it is disabling neightbor blocks, works when its set to use redstone, so that may not be a bug at all

**Comment by raoulvdberge** [comment]
I'd rather not make it draw RF every tick, but every 20 ticks?

**Comment by tomevoll** [comment]
its reporting 0 rf/t when turned off with redstone, but is drawing 10 rf/t, not sure if i did that changing what i just did, ill look at it

**Comment by raoulvdberge** [comment]
It can never draw 10 RF/t as the extractEnergy call is only called when isActive().

**Comment by raoulvdberge** [comment]
Oh no, it actually can, it's outside the if block, my mistake. :P Fixed

**Comment by tomevoll** [comment]
ya lol, i forgott to add that check when i moved it

**Comment by tomevoll** [comment]
you need the powerdraw outside the % 20 block, or it will draw every seccond not every tick :)

**Comment by raoulvdberge** [comment]
Fixed, thanks

**Comment by raoulvdberge** [comment]
Also there seems to be an issue with importers importing from ISidedInventory's slots they can't import from. (For example: importing at bottom of furnace sucking up items from input slot)

**Comment by tomevoll** [comment]
ya, need to check isidedinventory.getSlotsForFace(side); returns a int array of all slots available from the chosen side, using only getsizeInventory will ignore if it the slot is acually accessible from that side.

**Comment by tomevoll** [comment]
i can take  a look at the extractor

**Comment by tomevoll** [comment]
so canImport checks the filter as needed, so basicly the rest there would need a rewrite to support sided inventory properly, i should be able to do that pretty quickly :)

**Comment by tomevoll** [comment]
oh wait, i didnt look close enough, dont need alot of changes at all

**Comment by tomevoll** [comment]
hmm, i think the reason it pulls from the input slot is, the input is available from the side

**Comment by raoulvdberge** [comment]
So how does the hopper do it when putting a hopper *under* the furnace? Shouldn't it use that method too, and why wouldn't it take from the input slot too then......

**Comment by tomevoll** [comment]
the output slot is only avalible on the bottom, the input slot for item and fuel is the side, and input for item at top

**Comment by tomevoll** [comment]
private static final int[] slotsTop = new int[] {0};
    private static final int[] slotsBottom = new int[] {2, 1};
    private static final int[] slotsSides = new int[] {1};

**Comment by tomevoll** [comment]
ops,
Input at top
Fuel and input side
output bottom

**Comment by tomevoll** [comment]
omg i mixed it up again lol
0  is Slot for Item
1 is Fuel
2 is Output

**Comment by raoulvdberge** [comment]
hmm, but when having putting a importer ON a furnace, where the importer points at the furnace upwards, it takes from the input slot...

**Comment by tomevoll** [comment]
hmm ok, thats weird, ill test it

**Comment by tomevoll** [comment]
ya cause your not checking getSlotsForFace(side); so your pulling it from 0, canExtract wont report false, your not supose to ask it since that slot is not listed as available from that side

**Comment by tomevoll** [comment]
hmm [https://github.com/tomevoll/refinedstorage/commit/acee602eeb6c807e95ec53b0b8a367f5960b4169](url)

thats one way of doing it, but currentSlot should be using only the available slots instead of the complete size of the inventory.

**Comment by tomevoll** [comment]
ops dead link

Do you need to wait a few ticks between checking slots, isnt it better to just wait some ticks between each transfers

**Comment by tomevoll** [comment]
[example code](https://github.com/tomevoll/refinedstorage/commit/acee602eeb6c807e95ec53b0b8a367f5960b4169)

**Comment by raoulvdberge** [comment]
Thanks for the example code, I'll be doing a fix...

**Comment by tomevoll** [comment]
item pulling inserting is a mess really, worst part you do in a mod, so many things can go wrong :)

**Comment by tomevoll** [comment]
got plans for auto crafting ?

**Comment by tomevoll** [comment]
one thing that would be nice is if sneaking while placing a importer,  external storage or importer, reverse the direction, so i can as an example go behind a furnace sneak click when placing the export and it will face the furnace not me

**Comment by raoulvdberge** [comment]
Good idea, can you make an issue for it on Curse so I remember?

**Comment by tomevoll** [comment]
sure

**Comment by raoulvdberge** [comment]
Autocrafting is kinda meh to implement, but I'll see... :)

**Pull request closed without merging**
