### PR TITLE
Added translation into Korean

### PR DESCRIPTION
**Pull request by cookie5321**

### CODE REVIEW

**Comment by raoulvdberge** [comment]
I see not everything has been translated yet, can I merge this yet, or are you still working on it?

**Comment by 01QueN10** [comment]
I'm still working on this, but some of them are already translated. From line 84, they are.

**Comment by raoulvdberge** [comment]
I see, I'll merge when you're finished, then.

Thanks.

**Comment by 01QueN10** [comment]
All the translations are finished. It's not completed yet, but I'll refine it gradually.

**Comment by 01QueN10** [comment]
..? Why did TravisCI say it failed?

**Comment by raoulvdberge** [comment]
Don't mind that, the build server sometimes is glitchy.

**Comment by raoulvdberge** [comment]
Thanks!

**Pull request merged**
