### PR TITLE
draw item overlay scaled

### PR DESCRIPTION
**Pull request by tomevoll**

### CODE REVIEW

**Comment by tomevoll** [comment]
when i pulled it just pulled fr om the Fork, might be the client im using, your repo was added as remote for pull just didnt work

**Comment by raoulvdberge** [comment]
This will not render the durability bar and other item stuff because you deleted the renderItemOverlayIntoGUI call.

Maybe call renderItemOverlayIntoGUI before (with an empty string passed as message) renderSlotOverlay.

**Comment by tomevoll** [comment]
oh ofc, i can add that

**Comment by tomevoll** [comment]
tested and render bar fine :)

**Comment by tomevoll** [comment]
hmm ya i supose that would be a cleaner way todo it, call the renderitemoverlay with a empty string, do you want me to change it to that ?

**Comment by tomevoll** [comment]
can do shadow on the itemcount to if you want that

**Comment by tomevoll** [comment]
there :) includes shadow

**Comment by raoulvdberge** [comment]
Awesome!

**Comment by tomevoll** [comment]
:)

**Comment by raoulvdberge** [comment]
Maybe you could do the same font size for the RF/t usage display in the machine list in the controller? :D

**Comment by tomevoll** [comment]
sure :)

**Comment by tomevoll** [comment]
something like this ?

**Comment by raoulvdberge** [comment]
Yes! :D That is just beautiful. Did you remove this:
```
if (hoveringMachineStack != null) {
            drawTooltip(mouseX, mouseY, hoveringMachineStack);
        }
```
That tooltip is not needed anymore now.

**Comment by tomevoll** [comment]
ill remove it :)

**Pull request merged**
