### PR TITLE
Add datagen for Forge's block relocation blacklist, Packing Tape's block entity blacklist

### LINKED ISSUE #3105: tag nodes non movable
Need to find the tag and put it on all the blocks. Prevents moving with pistons/contraptions + prevents picking up with cardboard box and similar.

### PR DESCRIPTION
**Pull request by aeonic-dev**
This PR adds datagen for Forge's `forge:relocation_not_supported` block tag. The tag is used by Mekanism's cardboard box and other mods' methods for moving blocks, which inherently conflict with Refined Storage's data storage methods and result in lost/dangling data. As a side effect, we create colored block tags to mirror the item tags first, then add those and the remaining network node blocks to the blacklist tag.

We also add block entity tag datagen for [Packing Tape](https://www.curseforge.com/minecraft/mc-mods/packing-tape) (under `packingtape:blacklist/problematic`), another block moving mod that causes the same issue. 

There have been a few unresolved issues that were closed for various reasons (#2949, #2677, #2439) which this change addresses. Also closes #3105.

### CODE REVIEW

**Review by raoulvdberge — DISMISSED** [review]
Awesome, thanks!

**Comment by raoulvdberge** [comment]
@aeonic-dev Can you rebase on develop and add CHANGELOG entries?

**Comment by aeonic-dev** [comment]
Yep, on it.

**Review by raoulvdberge — APPROVED** [review]

**Comment by raoulvdberge** [comment]
Thanks!

**Pull request merged**
