### PR TITLE
Make ObjectHolders nicer :D

### PR DESCRIPTION
**Pull request by PixelRifts**
Annotating the class with @ObjectHolder(ModID) removes the need to prepend it everywhere! :)

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Nice! Can you target 1.16 branch though?

**Comment by PixelRifts** [comment]
Sure!

**Comment by PixelRifts** [comment]
Do I open another pr for that or what?
I'm really new to prs :)

**Comment by raoulvdberge** [comment]
Not sure. If you can't retarget the existing PR, you may open a new one :)

**Comment by Darkere** [comment]
Top right click edit. Then you can retarget the PR. TIL lol

**Comment by PixelRifts** [comment]
I opened a new pr. I could not get this to work

**Pull request closed without merging**
