### PR TITLE
Allow crafting upgrades to be used in the Interface to craft exported…

### LINKED ISSUE #158: Feature Request: Crafting upgrade in Interfaces
Would be nice to put a crafting upgrade into an interface so it can request an item to be crafted for export

### PR DESCRIPTION
**Pull request by dunkfordyce**
… items. fixes #158

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Does it also work when you have multiple items set up for exporting?

**Comment by raoulvdberge** [comment]
Also, the crafting task scheduler has to be written to NBT

**Comment by dunkfordyce** [comment]
Ah! Not as easy as I thought! Digging...

**Comment by raoulvdberge** [comment]
You could set up an array of 9 crafting task schedulers, I think.

**Comment by dunkfordyce** [comment]
I am not sure of the best way to write the NBT tags with an array of CraftingTaskSchedulers. I think I should use a NBTTagList but I would have to create a different implementation of CraftingTaskSchedulare.writeToNBT because currently it expects to write to an NBTCompoundTag

**Comment by raoulvdberge** [comment]
Something like this:
```java
NBTTagList l = new  NBTTagList();
for (int i = 0; i < 9; ++i)
{
   if (schedulers[i] == null) continue;
   NBTTagCompound t = new NBTTagCompound();
   t.setInteger("Id", i);
   NBTTagCompound x = new NBTTagCompound();
   schedulers[i].writeToNBT(x);
   t.setTag("Scheduler", x);
   l.appendTag(t);
}
```

**Comment by dunkfordyce** [comment]
Is the code at https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/apiimpl/autocrafting/CraftingTaskScheduler.java#L40 correct? It sets the scheduled item but should it not also call something like https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/apiimpl/autocrafting/CraftingTaskScheduler.java#L24 to actually request the crafting?

**Comment by raoulvdberge** [comment]
CraftingTaskScheduler doesn't need to handle calling `addCraftingTask`, the controller calls that already because it saves the crafting state.

**Comment by raoulvdberge** [comment]
I'll close this for now, since it is kinda tricky to implement indeed. Gonna try implementing this myself soon.

**Comment by raoulvdberge** [comment]
(Also, there are some bugs with the current CraftingTaskScheduler, I'll probably have to rework the craft on request system a bit)

**Comment by dunkfordyce** [comment]
Yea I couldn't get it to work! Sorry!

**Comment by raoulvdberge** [comment]
No problem & no need to excuse yourself, guess what, I couldn't get it to work myself :P

**Pull request closed without merging**
