### PR TITLE
JEI transfer picks the most common ingredient

### PR DESCRIPTION
**Pull request by Darkere**
When transfering items via JEI it will look up the most common item in the system and use that one instead of randomly picking. 
Implements #2921

### CODE REVIEW

**Comment by DarkHelmet433** [comment]
This would be really, really helpful!

**Comment by necauqua** [comment]
I played with this and my feedback is that I would also check for items that the system knows how to craft as a fallback - so if it has none of the variants it also looks up if it can craft one of them, this would help making patterns so much.

My existing scenario - making a pattern for a thing that needs blue dye, and I have a pattern to make vanilla dye from lapis, but of course I have none in the system.
And then there is a choice between vanilla blue dye that my system knows how to craft and some weird modded version that who knows how you need to even get that, and _of course_ the random selection picks up that weird modded version

But at least it stopped putting dark glass in all the recipes (if I have normal glass in the system), hurray

**Comment by necauqua** [comment]
One more thing to make it just perfect - also check player inventory for patterns, so that when player creates a whole pattern chain with JEI (very, very common thing in modpacks) it pick up the right variants all the time even if the system does not know about such items yet

**Comment by Darkere** [comment]
You know what... that is a great idea. Gonna blow peoples minds :D

**Comment by necauqua** [comment]
I think it should prefer player patterns (like players rarely carry patterns, and when they do it's exactly because they are making chain recipes) over most items in system.

I also see that you included player items as well, this one (separately from player patterns) should not take preference over the system maybe

**Comment by raoulvdberge** [comment]
> it picks up the right variants all the time even if the system does not know about such items yet

Doesn't this only work when you have none of all variants in the system?

If you have more of an item in your system than the pattern provides, the pattern would still be ignored.

**Comment by necauqua** [comment]
Well that's exactly what I am talking about in my previous message

**Comment by Darkere** [comment]
If I'm making patterns and there is an item that already exists in the system, I think it makes more sense to use that one rather than the item from a pattern that randomly can also be used in this recipe. 

More often than not I'll have plenty of these Items in the system and the recipe should use those rather than using the pattern for the special case I just made. 

For a concrete example, imagine you just made a pattern for Stone Bricks. I would still want any further patterns to still use the regular stone from the system. In fact it would be pretty weird if the machine casing recipe I make after this uses stone bricks rather than stone.

**Comment by Darkere** [comment]
working nicely now :)

**Comment by necauqua** [comment]
I got this btw:
<details>
<summary>exception</summary>

```
java.lang.UnsupportedOperationException: Crafting pattern is invalid
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.InvalidCraftingPattern.getOutputs(InvalidCraftingPattern.java:58) ~[refinedstorage:1.9.13] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.IngredientTracker.addAvailableStack(IngredientTracker.java:39) ~[refinedstorage:1.9.13] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.createTracker(GridRecipeTransferHandler.java:112) ~[refinedstorage:1.9.13] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.transferRecipeForCraftingGrid(GridRecipeTransferHandler.java:62) ~[refinedstorage:1.9.13] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.transferRecipe(GridRecipeTransferHandler.java:53) ~[refinedstorage:1.9.13] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.transferRecipe(GridRecipeTransferHandler.java:29) ~[refinedstorage:1.9.13] {re:classloading}
	at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:61) ~[jei:7.7.0.100]
```
</details>

**Comment by Darkere** [comment]
oh yeah good catch. fixed.

**Comment by NillerMedDild** [comment]
This feature would be greatly appreciated by many players, I hope you can find time at some point to review/merge this :x

**Comment by raoulvdberge** [comment]
Hi, I'm currently on vacation. I'll take a look at this next week.

**Pull request merged**
