### PR TITLE
Reverse direction on block if player is sneaking

### PR DESCRIPTION
**Pull request by tomevoll**
Might wanna ignore TileController is that pull not working again

### CODE REVIEW

**Comment by tomevoll** [comment]
what git client are you using, mine is def not doing the correct thing :)

**Comment by raoulvdberge** [comment]
You have to add features in branches, so you won't have conflicts when I push something :P

**Comment by raoulvdberge** [comment]
Anyhow, I got this piece of code already in a to-be-commited fix:
```    @Override
    public void onBlockPlacedBy(World world, BlockPos pos, IBlockState state, EntityLivingBase player, ItemStack itemStack) {
        super.onBlockPlacedBy(world, pos, state, player, itemStack);

        Block blockPlaced = state.getBlock();

        TileEntity tile = world.getTileEntity(pos);

        if (tile instanceof TileBase) {
            EnumFacing facing = BlockPistonBase.getFacingFromEntity(pos, player);

            if (player.isSneaking() && (blockPlaced == RefinedStorageBlocks.IMPORTER || blockPlaced == RefinedStorageBlocks.EXPORTER || blockPlaced == RefinedStorageBlocks.EXTERNAL_STORAGE)) {
                facing = facing.getOpposite();
            }

            ((TileBase) tile).setDirection(facing);
        }
    }```

**Comment by tomevoll** [comment]
features?, im new to git, can you explain how that works :)

**Comment by tomevoll** [comment]
oh
nm branches, didn't read that, got it, so branch, but dont i need a up to date source  to branch from ?

**Comment by raoulvdberge** [comment]
Yes, your branch needs to be up to date with mc-1.9 branch.

**Comment by tomevoll** [comment]
problem i got is i select pull from this repo into current repo, it does its thing and its not updating the files, and im unable to pull again as it says its up to date

**Comment by tomevoll** [comment]
updatefrom

i click Updatefrom button at the top, it merges this commits with my source, or is supose to,

**Comment by raoulvdberge** [comment]
I have no idea how that Git client works, I just use the command line and IntelliJ's built-in git stuff.

**Comment by tomevoll** [comment]
well looks like reverse pull request worked, basicly did a pull request on the Fork to merge the commits from here into the fork, seems to work

**Comment by tomevoll** [comment]
ugh frustrating, it merged the last commit you did lol, now says all is up to date even on github, exept if i look in the BlockExporter they are not up to date, trying to pull changes say it is up to date lol, im doing something wrong for sure

**Pull request closed without merging**
