### PR TITLE
Cherry picking and fixes

### PR DESCRIPTION
**Pull request by Darkere**
Last commit I'm not certain about. Couldn't find where it was used in the first place and didn't see anything broken either.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
I think this misses stuff like autocrafting insertion order? I'll cherry-pick myself.

**Comment by Darkere** [comment]
I left the insertion order out, since the PR I copied into the 1.16 branch is still open.

**Comment by raoulvdberge** [comment]
Ah you didn't close that PR? Can you close all the PRs that have been merged? I'll just cherry pick everything instead of merging from two sources.

**Comment by Darkere** [comment]
Done. It was just that one.

**Pull request closed without merging**
