### PR TITLE
Added an option to storage blocks to void items

### PR DESCRIPTION
**Pull request by geldorn**
**Feature description:**
This adds an option to storage blocks to void excess items (if the storage of the block is full it will simply destroy all items which would otherwise be inserted). This should be especially useful for auto generated items where you just want a specific amount of them (cobblestone comes to mind :) ). It is at least a partial implementation of #420 - I just added it to blocks only as i think it is more suitable for them, yet enabling it on other storage systems too should be no problem.

With the correct priority and white list settings you can keep a clean storage system without the fear of overflow.

**Notes:**
For the correct operation I also had to fix the problem that destroyed items are still counted to the cached network state. To counter this problem, I changed the ItemStack returned from the ItemStorageNBT.insertItem implementation to return a negative number if items where voided. In the TileController I also added logic to handle the negative ItemStacks correctly. I think the problem in #251 should be fixable with this too.

The icon added for the feature is only a quick draft as I'm not much of a designer.

<hr/>

**Screenshot of the void mode in action:**
image

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Thank you for the very good PR. Like that you fixed that issue with the storage count increasing!

Some remarks:

- Can you update your code so it respects the code style?
- Are the `VOID_EXCESS_OFF` and `VOID_EXCESS_ON` constants really needed?
- Small nit: change the translation to say "Void excess items" with a "yes" and "no" option instead of "on" and "off".

**Comment by geldorn** [comment]
Will do that tomorrow, the constants are not required.
Which coding style issues do you mean? I don't see any available coding style guide for the project.

**Comment by raoulvdberge** [comment]
There is no coding style guide, so that means you need to replicate the existing coding style.

**Comment by geldorn** [comment]
Well i tried to mimic it already, can you give me hints about the problems please?

**Comment by raoulvdberge** [comment]
Your if/else style here:
https://github.com/raoulvdberge/refinedstorage/pull/430/files#diff-2eb04851de70f77dda8d21e3d8bb9be5R533

Method decls on the same line here:
https://github.com/raoulvdberge/refinedstorage/pull/430/files#diff-d3739d17fca91ed0895f87eaff6debdcR309

**Comment by geldorn** [comment]
My IDE was folding them all to one line, this is why I didn't see it, coding style and naming should be fixed with the last commits.

**Comment by raoulvdberge** [comment]
Almost good:

- sidebutton.refinedstorage:void_excess.mode.yes/no can be removed, MC already has gui.yes / gui.no I think.
- There are still some coding style issues: spaces after if/ else: `if (` instead of `if(`

**Comment by raoulvdberge** [comment]
Thank you!

**Comment by geldorn** [comment]
With pleasure :)
I missed one if though, file TileStorage.java line 157

**Pull request merged**
