### PR TITLE
Improve a bit Russian Translation

### PR DESCRIPTION
**Pull request by CrossVas**
Feel free to chisel any part of this translation you want

### CODE REVIEW

**Comment by raoulvdberge** [comment]
What is the difference between this PR and #2257?

**Comment by CrossVas** [comment]
Actually my variant is more accurate and contain in terms of Block/item naming
Also achievements have been reformulated to avoid cacofonia

**Comment by Bytegm** [comment]
И это малая часть, я могу еще накоментировать.  ибо в твоём переводе больше неточностей чем в моём

**Comment by CrossVas** [comment]
@Bytegm how about collaboration?
Let's combine our efforts to make a decent translation

**Review by Externallex — COMMENTED** [review]
> @Bytegm how about collaboration?
> Let's combine our efforts to make a decent translation

каким образом?

**Comment by raoulvdberge** [comment]
?

**Pull request closed without merging**
