### PR TITLE
Fluid mode for storage monitor. Implements #2234

### PR DESCRIPTION
**Pull request by V1RTUOZ**
Added fluid mode to storage monitor.
Left Mouse Button when sneaking - extract fluid bucket from network.
Right Mouse Button with fluid container - store fluid.
Screenshots:
GUI
World

### CODE REVIEW

**Comment by V1RTUOZ** [comment]
For 1.12, but i can merge it into 1.15 probably.

**Comment by raoulvdberge** [comment]
Thx for the PR but 1.12 is not getting new features anymore. Please retarget for the 1.15 branch.

**Comment by V1RTUOZ** [comment]
@raoulvdberge can't make FluidRenderer render fluid in the world in 1.15

**Comment by raoulvdberge** [comment]
I don't know how to do so myself, so I'm unable to help with that unfortunately. I am going to close this PR as it targets 1.12, though.

**Pull request closed without merging**
