### PR TITLE
Port to 1.16.1

### PR DESCRIPTION
**Pull request by MoreThanHidden**

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Not cool. It would've been nice if you first discussed this with me, I prefer to do ports myself.

**Comment by MoreThanHidden** [comment]
Sorry, You honestly don't need to use it was just trying out some stuff myself though I'd submit it.

**Comment by raoulvdberge** [comment]
It's no big deal, honestly I appreciate the effort. I just like doing ports myself. I'll close this for now, this PR will still come in handy when I need to crossreference some mappings.

**Comment by raoulvdberge** [comment]
It's no big deal, honestly I appreciate the effort. Thank you.

I just like doing ports myself. I'll close this for now. This PR will still come in handy when I need to crossreference some mappings.

**Comment by MoreThanHidden** [comment]
Sorry again hope it's some help, I know where your coming from big fan of porting myself 😅, I just like to Fork and learn the codebase while porting, that way I can find better ways to improve the mods I'm working on, and I'll be more likely to submit bug fixes if I encounter anything in the future.

**Comment by raoulvdberge** [comment]
In that case, the PR certainly wasn't time wasted :)

**Pull request closed without merging**
