### PR TITLE
Add the ability to calculate in the CraftingSettingsScreen.java

### PR DESCRIPTION
**Pull request by danieldietzler**
Add the ability to enter mathematical expressions in the amountField.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
It doesn't really feel right to accept arbitrary Js expressions. Besides, the Js engine is removed in later java versions.

**Comment by Daniel-Dietzler** [comment]
So would you say there's a point on building a complete parser with computing laws etc? Or is it just to minor/irrelevant to put more effort into it?

**Comment by Daniel-Dietzler** [comment]
Apparently there is an open source project called "EvalEx" on GitHub which could be used.

**Comment by raoulvdberge** [comment]
I made a parser recently. We could include that.

**Comment by Daniel-Dietzler** [comment]
I'd appreciate it because often when you're building big multiblocks you need to have like 15x15x17 blocks or something. In those cases just typing 15x15x17 would be a minor but really neat feature.

**Comment by raoulvdberge** [comment]
I'll close this for now.

**Pull request closed without merging**
