### PR TITLE
Allow machines to work as cables

### PR DESCRIPTION
**Pull request by tomevoll**

### CODE REVIEW

**Comment by tomevoll** [comment]
i did not go threw all of your code to see if all exporters use the Helper for export, another way to do it could be to use TileEntityHopper.putStackInInventoryAllSlots(inventoryIn, stack, side) it will return any leftover items not transfered and will do the checks needed like isvalidforslot and so on, it also handles if the slot is available from the side you access the block on for mods that use a sided inventory.

**Comment by tomevoll** [comment]
using the machines as cable is not working correctly, need to change the scan itself to make it work, its semi working,

I don't recommend a merge

**Comment by raoulvdberge** [comment]
You probably took the wrong approach by extending every machine with TileCable.

**Comment by raoulvdberge** [comment]
Okay, I think I got this. Pushing in a sec.

**Comment by tomevoll** [comment]
:)

**Comment by tomevoll** [comment]
ya it was working up to the  point you connect a cable to another machine and it didnt make a connection threw that.

**Comment by raoulvdberge** [comment]
I also realized cables don't need a TE, so I removed that too.

**Comment by raoulvdberge** [comment]
af4f3e8b40b4f1aeaad36a472780fbc1085b4507 :)

**Comment by tomevoll** [comment]
make sure to change the block to extend Block not BlockContainer if you remove it,i think forge expect a tile if BlockContainer is used

**Comment by raoulvdberge** [comment]
I heard BlockContainer is old MC code, and kinda deprecated, so I don't use it.

**Comment by tomevoll** [comment]
looks good :)

**Comment by raoulvdberge** [comment]
This update is gonna be pretty great.

**Comment by tomevoll** [comment]
ah, well blockContainer is just Block but with the interface ITileEntityProvider and it also automaticly remove the tile from the world on block break

**Comment by tomevoll** [comment]
public void breakBlock(World worldIn, BlockPos pos, IBlockState state)
    {
        if (hasTileEntity(state) && !(this instanceof BlockContainer))
        {
            worldIn.removeTileEntity(pos);
        }
    }

**Comment by tomevoll** [comment]
oh wait thats weird, i guess it doesnt matter then :)

**Comment by tomevoll** [comment]
nm the tile removal is done in BlockContainer not block, but you can just implement ITileentityProvider manually, no difference really.

in BlockContainer:
public void breakBlock(World worldIn, BlockPos pos, IBlockState state)
    {
        super.breakBlock(worldIn, pos, state);
        worldIn.removeTileEntity(pos);
    }

**Comment by tomevoll** [comment]
did you look at the stack transfer, it was not filling up furnaces as an example until the furnace was all empty i changed canpush and adjusted the code in pushToInventory and pushtoslot, also included the isitemvalid in pushtoinv, you did a loop threw all slots there without checking :) whatever was not transfered gets pushed back in to storage

**Comment by tomevoll** [comment]
in GuiBase use this one to render the slot overlay :)

 if (withOverlay) {
        	renderSlotOverlay(stack, message,x,y);
 }

private void renderSlotOverlay(ItemStack stack, String text, int x, int y) {
		if (text != null) {
			GlStateManager.pushMatrix();
        	        GlStateManager.translate(x, y, 1);
			GL11.glScalef(0.5f, 0.5f, 1);

			int stringWidth = fontRendererObj.getStringWidth(text);
			GlStateManager.disableLighting();
			GlStateManager.disableRescaleNormal();
			GlStateManager.depthMask(false);
			GlStateManager.enableBlend();
			GlStateManager.blendFunc(770, 771);
			GlStateManager.disableDepth();
			fontRendererObj.drawString(text, 30-stringWidth, 22, 16777215);
			GlStateManager.enableDepth();
			GlStateManager.enableTexture2D();
			GlStateManager.depthMask(true);
			GlStateManager.enableLighting();
			GlStateManager.disableBlend();
			GlStateManager.popMatrix();
		}
	}


or make your own :) scales down the text size. looks better i think.

**Comment by raoulvdberge** [comment]
Does that render the "glint" on enchanted items too?

**Comment by tomevoll** [comment]
thats just the text

**Comment by raoulvdberge** [comment]
You can PR that if you want!

**Comment by tomevoll** [comment]
hmm is there a easy way to get my fork up to current ?

**Comment by raoulvdberge** [comment]
git pull?

**Comment by tomevoll** [comment]
ya but it didnt work :O

**Comment by tomevoll** [comment]
k im just gonna rebranch :O

**Pull request closed without merging**
