### PR TITLE
Fix for #1147

### PR DESCRIPTION
**Pull request by ineternet**
Read commit for explanation.

Tested before+after, could reproduce unintended (before fix) and intended (after fix) results.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
I'm not sure if I like the current behavior more. It's more predictable (as an end-user) to say "is the disk empty" then to assume "are the disk contents all insertable"?

@way2muchnoise, what do you think?

**Comment by way2muchnoise** [comment]
Both behaviours make sense to me, mostly personal preference imo. So all up to you @raoulvdberge ;)

**Comment by ineternet** [comment]
I agree that it might be more intuitive to assume that only an empty disk is a fully transferred disk. This is really based on personal preference, whether you want to know if it's done transferring or "waiting for free space".

In that case, assuming you want to keep the old design, why's the issue still open? This PR is all I could think about when I read the issue.

**Comment by ineternet** [comment]
I've changed the behaviour.

The disk now does *not* get moved to an output slot when it cannot be transferred, but is instead skipped, meaning that the next possible disk (second, third slots) is starting to import. As soon as there's space for more from the first disk, it stops and prioritizes the first disk again, until it is empty (moved to output) or untransferable (skipped over, continuing with second/third disk).

**Comment by raoulvdberge** [comment]
Thanks!

**Pull request merged**
