### PR TITLE
restrict gregtech rendering ban to wires and machines

### PR DESCRIPTION
**Pull request by Darkere**
They are using some weird stuff for their Itemregistration. 
Translationkey is "unnamed". That's why over resource location. 

Machines don't actually crash they just render nothing so that part is not strictly required.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Can you convert this logic to another method and make some of the boolean logic clearer (adding if statements etc.)

Please also change the changelog entry as well :)

**Comment by raoulvdberge** [comment]
I can't merge, your changelog is causing a conflict.

**Comment by Darkere** [comment]
huh never used githubs conflict tool before I think that worked?

**Comment by raoulvdberge** [comment]
thx

**Pull request merged**
