### PR TITLE
New API method to allow to connect graphically other tiles to cables

### PR DESCRIPTION
**Pull request by davidog23**
I was writing a open computer driver for Refined Storage and I need to connect graphically the cables to another tile which doesn't implement INetworkNode nor INetworkMaster.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Thanks for the PR. However I don't think a `Set<Class>` is flexible enough. Can we perhaps change that to a `Set<Predicate<TileEntity>>`? Also, the `connectableElements` field in `BlockCable` is confusing. Can we centralize that to the API?

**Comment by davidog23** [comment]
Something like this?

**Comment by way2muchnoise** [comment]
Wouldn't it be easier to just make some interface like `IConnectable` which has that one method `shouldConnect` or  `canConnect` or maybe not even have a method? (I guess default it to true, so you can have some requirements in your TE)

**Comment by davidog23** [comment]
The problem with that is the fact I must to connect the TE to the cable without modifying the TE signature.
Creating IConnectable would be easier but more restrictive with code you can't modify.

**Comment by way2muchnoise** [comment]
Any reason you can't change the TE signature? Or what is the use case here?

**Comment by davidog23** [comment]
The TE I want to connect is the Adapter from Open Computers and the use I propose is:
`@RSAPIInject
public static IRSAPI RSAPI;`
Inside my init:
`RSAPI.getConnectableConditions().add(tile -> tile instanceof Adapter);`

**Comment by way2muchnoise** [comment]
Being a cable might even better just be a capability. Will have to discus this with @raoulvdberge some time.

**Comment by raoulvdberge** [comment]
Yep, a CableConnector capability would be cool. Are you able to bind such a cap to the adapter, @davidog23?

**Comment by raoulvdberge** [comment]
On the topic of the PR, it's nearly perfect. Can you move the ` add(tile -> tile instanceof INetworkMaster || tile instanceof INetworkNode)` call to `ProxyCommon`. Other API interactions are happening there too.

**Comment by raoulvdberge** [comment]
Thank you!

**Comment by davidog23** [comment]
I was reading about the capability system but It confuses me, but I think I would be able to bind the TE with the CableConnector capability.

**Pull request merged**
